name: realm_example
description: Demonstrates how to use the Realm SDK for Flutter.
version: 2.0.0-alpha.2

publish_to: "none"

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  realm:
    path: ../
  characters: 1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
